LIBNAME HOME 'L:\ECOG and LC' ;
RUN;

TABLE 3;
**SUBJECTIVE COGNITIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2  NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_rostral2  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2  NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_rostral2  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1  NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_CAUDAL1  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

**SUBJECTIVE MEMORY DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1  NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_rostral2  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1  NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_CAUDAL1  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2  NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_rostral2  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1  NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_CAUDAL1  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE EXECUTIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2  NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_rostral2  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1  NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_CAUDAL1  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2  NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_rostral2  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1  NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_CAUDAL1  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE LANGUAGE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2  NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_rostral2  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1  NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_CAUDAL1  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2  NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_rostral2  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1  NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_CAUDAL1  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE VISUOSPATIAL DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2  NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_rostral2  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1  NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_CAUDAL1  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2  NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_rostral2  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1  NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_CAUDAL1  ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


*TABLE 4;
**SUBJECTIVE COGNITIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 cognition / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 cognition/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 cognition/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 cognition/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

**SUBJECTIVE MEMORY DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 memory_v3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 memory_v3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 MEMORY_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 MEMORY_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE EXECUTIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 commonef_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 commonef_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 commonef_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 commonef_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE LANGUAGE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 fluency_v3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 fluency_v3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 fluency_v3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 fluency_v3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE VISUOSPATIAL DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 visuospatial_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 visuospatial_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 visuospatial_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 visuospatial_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


*SUPPLEMENTAL TABLE 1;
**SUBJECTIVE COGNITIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

**SUBJECTIVE MEMORY DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_decline Zmemory_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE EXECUTIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE LANGUAGE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE VISUOSPATIAL DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zvisuospatial_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zvisuospatial_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3  Zvisuospatial_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3  Zvisuospatial_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;





*SUPPLEMENTAL TABLE 2;
**SUBJECTIVE COGNITIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3  zcog_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;

**SUBJECTIVE MEMORY DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


**SUBJECTIVE EXECUTIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


**SUBJECTIVE LANGUAGE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


**SUBJECTIVE VISUOSPATIAL DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zvisuospatial_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zvisuospatial_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3  Zvisuospatial_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3  Zvisuospatial_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;










**********************;
REMOVING MCI OUT;
**********************;

**SUBJECTIVE MEMORY DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;


*TABLE 3;
**SUBJECTIVE COGNITIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 cognition / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 cognition/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 cognition/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 cognition/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

**SUBJECTIVE MEMORY DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 memory_v3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 memory_v3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 MEMORY_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 MEMORY_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE EXECUTIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 commonef_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 commonef_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 commonef_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 commonef_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE LANGUAGE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 fluency_v3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 fluency_v3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 fluency_v3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 fluency_v3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE VISUOSPATIAL DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 visuospatial_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 visuospatial_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 visuospatial_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 visuospatial_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


*SUPPLEMENTAL TABLE 1;
**SUBJECTIVE COGNITIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

**SUBJECTIVE MEMORY DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_decline Zmemory_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE EXECUTIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE LANGUAGE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE VISUOSPATIAL DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zvisuospatial_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zvisuospatial_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3  Zvisuospatial_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3  Zvisuospatial_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;





*SUPPLEMENTAL TABLE 2;
**SUBJECTIVE COGNITIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3  zcog_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;

**SUBJECTIVE MEMORY DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


**SUBJECTIVE EXECUTIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


**SUBJECTIVE LANGUAGE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


**SUBJECTIVE VISUOSPATIAL DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zvisuospatial_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zvisuospatial_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3  Zvisuospatial_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3  Zvisuospatial_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;







**********************;
REMOVING MCI OUT NO OBJECTIVE COGNITION;
**********************;

**SUBJECTIVE MEMORY DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;


*TABLE 3;
**SUBJECTIVE COGNITIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

**SUBJECTIVE MEMORY DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE EXECUTIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE LANGUAGE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog05162021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE VISUOSPATIAL DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


*SUPPLEMENTAL TABLE 1;
**SUBJECTIVE COGNITIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

**SUBJECTIVE MEMORY DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_decline / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_decline / DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE EXECUTIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE LANGUAGE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


**SUBJECTIVE VISUOSPATIAL DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zvisuospatial_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zvisuospatial_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3  Zvisuospatial_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog03222021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0 AND rMCI_cons_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3  Zvisuospatial_decline/ DIST=NOR;
 repeated subject=VETSAID(CASE) / type=cs;
 RUN;





*SUPPLEMENTAL TABLE 2;
**SUBJECTIVE COGNITIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECP_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 zcog_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECI_AVG =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3  zcog_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;

**SUBJECTIVE MEMORY DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPMEM =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIMEM =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zmemory_V3/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


**SUBJECTIVE EXECUTIVE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPEF =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIEF =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zef_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


**SUBJECTIVE LANGUAGE DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPLAN =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECILAN =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zfluency_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


**SUBJECTIVE VISUOSPATIAL DECLINE;
***PARTICIPANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zvisuospatial_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECPVPA =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3 Zvisuospatial_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;

***INFORMANT RATING;
PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_ROSTRAL2 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_ROSTRAL2 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3  Zvisuospatial_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;


PROC GENMOD DATA= HOME.lcecog02232021;
WHERE STD_CNR_CAUDAL1 NE . AND MRI_EXCLUDE_V3 = 0;
 CLASS VETSAID CASE ;
 MODEL ZECIVPA =  STD_CNR_CAUDAL1 ZAGE_V3 Zcesdtot_V3 Zcharlson_V3  Zvisuospatial_decline/ DIST=NOR;
 repeated subject=CASE / type=cs;
 RUN;






























































































































